# Generated by Django 5.0.14 on 2026-03-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLConverterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sql_converter_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('converted_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('conversion_count', models.IntegerField(default=0)),
            ],
        ),
    ]
